day1/07_Collaboration/02_Collaboration.md
=> Add remote branch listing

day1/06_Server/04_Connect_Local_Remote.md
=> More clear instructions for the Gnome keyring helper

day1/05_Branching/03_Reset_Commit.md, day2/01_Workflows/09_Rebase_Squash.md
=> Enhance 'git reset' for local and remote base resets

day2/01_Workflows/07_Gitlab_Workflow.md
Also add a cleanup CLI command to the handout.
=> Fix deleting local branches without remote tracking branches

day1/01_Introduction/03_Basics.md, day1/01_Introduction/05_Installation.md, day1/01_Introduction/06_Gui_Clients.md, day1/04_Commits/04_History.md, day1/06_Server/01_Intro.md, day2/01_Workflows/02_Centralized.md, day2/01_Workflows/03_Feature_Branch.md, day2/01_Workflows/04_Gitflow.md, day2/01_Workflows/06_Github_Flow.md, day2/01_Workflows/07_Gitlab_Workflow.md, day2/02_Integrations/02_IDEs.md, day2/02_Integrations/03_Puppet_Environments.md, day2/03_CI/02_Jenkins.md, day2/03_CI/04_Gitlab_CI.md, day2/03_CI/05_Gitlab_Pipelines.md
=> Adjust image width for printed handouts

day2/05_Git_Hints/31_LFS.md
Adds a short overview on a single slide for usage of Git Large File Storage.
fixes #71
=> Add slide for usage of Git LFS

day2/03_CI/05_Gitlab_Pipelines.md
Adds a lab slide instructing on how to create a schedule for running pipelines.
fixes #28
=> Add lab slide for pipeline schedules

day2/03_CI/03_Gitlab_CI.md
=> Wrong details about built-in runner

day2/02_Integrations/04_Hooks.md
=> Reorganise use cases

day1/06_Server/04_Connect_Local_Remote.md
=> Add slide about the credential helper

day2/04_Gitlab_Hints/06_API.md, day2/04_Gitlab_Hints/07_Applications.md
=> Rename Applications to Integrations

day1/04_Commits/04_History.md
=> Add git blame entry in the good commits section

day1/06_Server/01_Intro.md
I would not want to recommend the currently mentioned git Server options.
=> Update git server alternatives to more current and maintained options

day2/03_CI/03_Gitlab_CI.md
- Since Docker is only one product and there are and will be alternatives
=> Make Container pages more runtime-agnostic

day1/05_Branching/03_Reset_Commit.md
=> Add slide about git-revert

day1/00_Organisation/01_Intro.md
=> Add introduction slide for attendees

README.md
=> Remove trainer intro tip

day2/01_Workflows/08_Practical_Workflow_Examples.md
- Add GitHub Actions mention
- Fix missing line break
=> Minor fixes on Workflow Examples Icinga2

day2/03_CI/03_Gitlab_CI.md
Should be sufficient to wrap the head around the concept
Fixes #100
=> Add example uses for CI variables

day2/02_Integrations/04_Hooks.md
- Combined client and server side hooks on one slide
- Moved web hooks to handout only
- Reworked handout to be more concise
Fixes #162
=> Rework git hooks section

day1/00_Organisation/01_Intro.md, day1/01_Introduction/03_Basics.md, day1/03_Basics/02_Start.md, day1/03_Basics/03_Changes.md, day1/03_Basics/04_Status.md, day1/03_Basics/05_Gitignore.md, day1/04_Commits/04_History.md, day1/04_Commits/05_Amend.md, day1/05_Branching/01_Intro.md, day1/05_Branching/02_head_smart_pointers.md, day1/05_Branching/03_Reset_Commit.md, day1/06_Server/03_Gitlab_Installation.md, day1/06_Server/04_Connect_Local_Remote.md, day1/07_Collaboration/02_Collaboration.md, day1/07_Collaboration/04_Advanced.md, day2/01_Workflows/02_Centralized.md, day2/01_Workflows/06_Github_Flow.md, day2/01_Workflows/09_Rebase_Squash.md, day2/03_CI/03_Gitlab_CI.md, day2/03_CI/04_Gitlab_Pipelines.md
=> Normalize punctiation in bullet point list

day2/01_Workflows/07_Gitlab_Workflow.md
- analyse is BE, rest of the training use AE
=> [Draft] Normalize use of AE and BE

day1/03_Basics/05_Gitignore.md, day1/05_Branching/01_Intro.md, day1/05_Branching/02_head_smart_pointers.md, day1/06_Server/04_Connect_Local_Remote.md, day1/07_Collaboration/02_Collaboration.md, day1/07_Collaboration/04_Advanced.md, day2/01_Workflows/02_Centralized.md, day2/01_Workflows/03_Feature_Branch.md, day2/01_Workflows/04_Gitflow.md, day2/01_Workflows/06_Github_Flow.md, day2/01_Workflows/07_Gitlab_Workflow.md, day2/01_Workflows/08_Practical_Workflow_Examples.md, day2/01_Workflows/09_Rebase_Squash.md, day2/01_Workflows/10_Delete_Remote_Branches.md, day2/02_Integrations/04_Hooks.md, day2/03_CI/02_Travis_CI.md, day2/03_CI/03_Gitlab_CI.md, day2/04_Gitlab_Hints/02_UI.md, day2/05_Git_Hints/01_Intro.md, day2/05_Git_Hints/11_Subtree.md
=> Rename master to main

day2/00_Repetition/01_Intro.md, showoff.json
Added before the workflow slides.
Tried a bullet point list, but it didn't fit on the page. Suggestions are welcome
Fixes #118
=> Add a day2 repetition slide

day2/01_Workflows/09_Rebase_Squash.md
=> Remove the ask the trainer note

day2/00_Repetition/01_Intro.md
=> Change reptition to reflect day1 better

day1/04_Commits/04_History.md
@theFeu I would propose this as a fix for #152 
Fixes #152
=> Add small bonus to git history lab regarding git log

day2/00_Repetition/01_Intro.md
=> Fix typos in repetion

day2/05_Outlook/01_GitLab_Features.md
- More descriptions and use case examples
- Removed Issue Board lab, since trivial
Fixes #198
=> Refactor further Gitlab features at the end of training

day1/01_Introduction/01_Intro.md, day1/01_Introduction/04_Basics.md, day1/03_Basics/01_Intro.md, day2/01_Workflows/05_Gitlab_Workflow.md, day2/03_CI/04_Gitlab_Pipelines.md
Optimized some parts to be more readable in the PDFs
=> Update some sizing to fix PDF handout

day2/03_CI/03_Gitlab_CI.md
Since a Lab would take up some time, I decided against it for now.
However, if time allows, we could add a lab in the future.
Fixes #201
=> Add slide regarding GitLab CI Pipeline Efficiency

day1/03_Basics/03_Changes.md
=> fixing typo

day1/07_Collaboration/02_Collaboration.md
=> fixin spell

day1/04_Commits/01_Intro.md
=> headline change

day1/04_Commits/04_History.md
=> examine commit history typo

day1/03_Basics/05_Gitignore.md
=> Add the ! notation example for gitignore

day1/01_Introduction/03_Configuration.md
=> Add example of changing colors in gitconfig

day1/00_Organisation/01_Intro.md
=> Detelte slide about BBB from the Orga/Intro

day2/03_CI/03_Gitlab_CI.md, day2/03_CI/04_Gitlab_Pipelines.md, day2/04_Summary/01_Summary.md
Fixes #257
Fixes #261
Fixes #260
Fixes #262
=> Various improvements

day1/06_Server/01_Intro.md
=> Rework git server intro

day2/03_CI/03_Gitlab_CI.md
=> Fix example in GitLab CI Variables

day1/00_Organisation/01_Intro.md
=> Add orga slide about gitlab
